### ISSUE TITLE
Python to .NET library porting for controlling devices

### ISSUE THREAD

**Issue by lk-davidegironi** [alexforencich/xfcp#4]
Hi Alex,

as I solved my issue with I2C https://github.com/alexforencich/xfcp/issues/3 I've worked on

- .NET library implementation written in C#
- I2C IP that loads data from i2C (24c256). I'm actually using it for Ethernet interface settings registers (ip, gateway...). It uses your i2c_master_wbs_8 

The library it's a porting of your python XFCP code. It's a minimal library implementation.
Interface implemented:

- UART: System.IO.Ports
- two Ethernet mode: System.Net.Sockets.UdpClient and System.Net.Sockets

Nodes implemented:

- Switch
- Memory
- I2C

There is also a minimal GUI.

It's in _beta_ stage, I'm working on it, but if anyone interested I may release this library.

I still have some issue on FPGA side, XFCP sometimes stuck when many packages are sent, I've to investigate it further, I hope not to bother you, in case I will open a new issue, I'm thinking about building something like a watchdog to reset the AXI lines of XFCP whenever it stuck. Wondering if you ever get this kind of behavior and how you solve it.

![xfcp_protoview_sample_01](https://user-images.githubusercontent.com/90449776/156746497-5e2eb837-402e-48a0-b9c4-bbe52943e129.PNG)

**Comment by Mr-Liu-f** [comment]
hi lk-davidegironi can you share the XFCP .NET GUI thanks

**Comment by lk-davidegironi** [comment]
Hello, find attached.
Just as a note, I've not used it, I've developed my own protocol indeed.
[XFCPProto.zip](https://github.com/alexforencich/xfcp/files/13068030/XFCPProto.zip)
